diffusion_sampler:
  run_dir: "trained_models/face"
  image_shape: [128, 128, 3]
  num_steps: 2000
  num_samples_to_take: 250
  sampling_window: [100, 1900]
  initial_step: 0 # [0, num_steps]
  batch_size: 16
  selection_strategy: block
  sigma: 10
  data_domain: image
  hard_consistency: false
  initial_measurement: false
  guidance_method: dps
  guidance_kwargs:
    omega: 1
  plotting_interval: 100


  batch_design:
    num_samples: 2
    omega_multiplier: 1
    lamda: 0.0001
    learning_rate: 5000
    num_gradient_steps: 100
